[package]
name = "fuel_rail_analysis"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oem_types = { git = "https://github.com/frsrblch/oem_types" }
chrono = "0.4.19"